export enum TransactionStatus {
  POSTED = 'POSTED',
  PENDING = 'PENDING',
  FAILED = 'FAILED',
  REVERSED = 'REVERSED',
}

// Specific Schema for Loan Account Master
export interface LoanMasterRecord {
  [key: string]: any;
  id: string; // Primary Key (Account Number)
  accountNumber: string;
  outstandingPrincipal: number;
  dateLastActivity: string;
  interestRate: number;
  productCode: string;
  status: string;
}

// Specific Schema for Loan Transaction History
export interface LoanTransactionRecord {
  [key: string]: any;
  id: string; // Primary Key (Txn ID)
  accountNumber: string;
  captureDate: string;
  transactionAmount: number;
  transactionType: string;
  description: string;
}

// Generic type for the app to use
export type DataRecord = LoanMasterRecord | LoanTransactionRecord;

export enum DiscrepancyType {
  MATCH = 'MATCH',
  VALUE_MISMATCH = 'VALUE_MISMATCH', // Amounts don't match
  TIMING_DIFF = 'TIMING_DIFF', // Dates slightly off
  STATUS_DIFF = 'STATUS_DIFF',
  META_DIFF = 'META_DIFF', // Description or non-critical fields
  MISSING_IN_NEW = 'MISSING_IN_NEW',
  MISSING_IN_OLD = 'MISSING_IN_OLD',
}

export interface DiscrepancyReason {
  code: string;
  label: string;
  description: string;
  label_zh?: string;
  description_zh?: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
}

export interface ComparisonResult {
  recordId: string;
  oldRecord?: DataRecord;
  newRecord?: DataRecord;
  type: DiscrepancyType;
  diffs: string[]; // List of field names that differ
  reasonCode?: string; // Links to DiscrepancyReason
  aiAnalysis?: string; // Generated by Gemini
}

export interface ComparisonStats {
  totalRecords: number;
  matchCount: number;
  mismatchCount: number;
  matchRate: number;
  discrepancyBreakdown: Record<string, number>; // ReasonCode -> Count
  fieldStats: Record<string, { total: number; mismatch: number }>; // Field -> Stats
}

// --- Job Execution Types ---

export enum RunStatus {
  QUEUED = 'QUEUED',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED'
}

export type SchemaType = 'LOAN_MASTER' | 'LOAN_TXN';

export interface ComparisonConfig {
  id: string;
  name: string;
  schemaType: SchemaType;
  sourceTable: string;
  targetTable: string;
  description: string;
}

export interface JobRun {
  runId: string;
  configId: string;
  configName: string;
  startTime: string; // ISO string
  endTime?: string;
  status: RunStatus;
  stats?: ComparisonStats;
  results?: ComparisonResult[];
  schemaType?: SchemaType;
}